version: '3.9'
services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app/backend
    command: bash -lc "pip install -r backend/requirements.txt && uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -lc "npm install && npm run dev -- --host"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend 